[general]
debug=true
use-generation-check = false

[[mob]]
name="naturalist:boar"
[[mob.rule]]
name="vicious-hogs"
type="all"
set.on-hurt="all"
set.attack="player"
set.size=[150,200]

[[mob]]
name="minecraft:glow_squid"
[[mob.rule]]
name="rarer-glow-squid"
type="control"
spawn.at-y="<30"
spawn.count=[1,2]
repeat=400

[[mob]]
name="minecraft:zombie"
[[mob.rule]]
name="beach-lackeys"
type="natural"
biome-tag="minecraft:is_beach"
spawn.convert="rottencreatures:zombie_lackey"
run=50
[[mob.rule]]
type="natural"

[[mob]]
name="minecraft:turtle"
[[mob.rule]]
name="twortles"
spawn.count=[1,2]
type="natural"

[[mob]]
name="pesky_seagulls:seagull"
[[mob.rule]]
name="reduce-seagulls"
spawn.count=1
run=50
type="natural"

[[mob]]
name="minecraft:camel"
[[mob.rule]]
name="desert-camels"
biome="minecraft:desert"
type="control"
spawn.count=[1,2]
spawn.additional-checks="yes"
repeat=400

[[mob]]
name="hybrid_aquatic:hermit_crab"
[[mob.rule]]
name="fewer-hermit-crabs"
type="natural"
run=33

[[mob]]
name="hybrid_aquatic:coconut_crab"
[[mob.rule]]
type="all"
biome="oceania:rocky_beach"
spawn.convert = "hybrid_aquatic:dungeness_crab"
run=100

[[mob]]
name="ecologics:coconut_crab"
[[mob.rule]]
type="all"
spawn.convert = "hybrid_aquatic:coconut_crab"
set.size=[200,300]
run=100

[[mob]]
name="hybrid_aquatic:coconut_crab"
[[mob.rule]]
type="natural"
set.size=[200,400]
run=75

[[mob]]
name="minecraft:cod"
[[mob.rule]]
type="block"

[[mob]]
name="minecraft:salmon"
[[mob.rule]]
type="block"

[[mob]]
name="minecraft:squid"
[[mob.rule]]
type="block"

[[mob]]
name="minecraft:pufferfish"
[[mob.rule]]
type="all"
spawn.convert = "hybrid_aquatic:blowfish"

[[mob]]
name="artifacts:mimic"
[[mob.rule]]
set.health=40

[[mob]]
name="frycmobvariants:corsair"
[[mob.rule]]
name="beach-corsairs"
biome-tag="#minecraft:is_beach"
type="control"
spawn.count=1
spawn.additional-checks="yes"

[[mob]]
name="minecraft:skeleton"
[[mob.rule]]
name="no-beach-skeletons"
biome-tag="#minecraft:is_beach"
type="block"

[[mob]]
name="*"
[[mob.rule]]
type="all"