#Small Ships Heraldry client settings
#Sat Jul 25 11:38:20 PDT 2026
brushColor=\#FFB24CD8
previewYaw=174.66753
gridVisible=true
editorMode=paint
previewStage=4
tool=brush
fillMode=replace
brushSize=1
previewPitch=-12.7187395
previewZoom=1.4815431
mirrorVertical=false
strokeMode=freehand
mirrorHorizontal=false
