[creativeModeTabs]
	enableCreativeModeTabs = false
	enableBerryTheme = false
	disabledCreativeModeTabs = ["minecraft:op_blocks"]
	syncSelectedCreativeModeTab = false
[stackGroups]
	enableStackGroups = true
